name: Pipeline name  # Имя пайплайна
env:  # Переменные среды
  VARIABLE: "var"

on:  # Триггеры для запуска пайплайна
  workflow_dispatch:  # Ручной запуск через UI Гитхаба
  pull_request:  # Для пул реквестов
  push:

jobs: # Список джоб
  validation: # Имя джобы
    runs-on: ubuntu-20.04
    steps:   # Действия для нашей job
      - name: Clone repo  # Клонируем наш репозиторий
        uses: actions/checkout@v2

      - name: Set up Python "3.10.14"
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.14

      - name: Install dependencies  # Устанавлиаем Python зависимости
        run: |
          echo "We are in directory:"
          pwd
          ls
          python -m pip install --upgrade pip
          echo "Install requirements"
          pip install -r requirements.txt
          echo "Run setup"
          pip install -e .

      - name: Run unit tests for model  # Запускаем тестики для модели
        run: |
          python ml_project/tests/test_full_train_fit_pipeline.py
          python ml_project/tests/data/test_get_dataset.py
          python ml_project/tests/features/test_transformer.py
          python ml_project/tests/models/test_train_model.py
        
      - name: Run unit tests for app # Запускаем тестики для приложения
        run: |
          python -m online_inference.tests
          
